[package]
name = "copy_from_derive"
version = "0.1.0"
authors = ["Kunal Arya <kunalarya@gmail.com>"]
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
quote = "1.0"
