name: ci

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Rustfmt (sunfish-core)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sunfish-core
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install black==21.7b0
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - name: Check python formatting (black)
        run: black --check .
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
        working-directory: ./sunfish-core/

  check:
    name: Check (sunfish-core)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run cargo check
        run: cargo check
        working-directory: ./sunfish-core/

  clippy:
    name: Clippy (sunfish-core)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sunfish-core
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - run: cargo clippy
        working-directory: ./sunfish-core/

  test:
    name: Cargo Test (sunfish-core)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sunfish-core
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - name: Run cargo test
        run: cargo test
        working-directory: ./sunfish-core/
